name: Upload
on:
  pull_request:
    branches:
      - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        competition: [m5-forecasting-accuracy]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          slug: ${{ matrix.competition }}

      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: ${{ matrix.competition }}
          title: ${{ matrix.competition }}
          code_file: ./output/${{ matrix.competition }}.ipynb
          language: python
          kernel_type: notebook
          is_private: false
          competition_sources: ${{ matrix.competition }}
