name: Test
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        competition: [m5-forecasting-accuracy]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Flake8
        run: flake8 .

      - name: Black
        run: black --check .
