name: Upload
on:
  push:
    branches:
      - master
  schedule:
    # Run this job every 12 hours.
    - cron: "0 */12 * * *"

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        competition:
          # [
          #   m5-forecasting-accuracy,
          #   liverpool-ion-switching,
          #   bengaliai-cv19,
          #   jigsaw-multilingual-toxic-comment-classification,
          # ]
          - slug: m5-forecasting-accuracy
            id: m5-forecasting-accuracy
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          slug: ${{ matrix.competition.slug }}

      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: top-scoring-kernels-${{ matrix.competition.id }}
          title: "Top Scoring Kernels: ${{ matrix.competition.id }}"
          code_file: ./output/${{ matrix.competition.slug }}.ipynb
          language: python
          kernel_type: notebook
          is_private: false
          competition_sources: ${{ matrix.competition.slug }}
